language: ruby
rvm:
  - ruby-head
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - jruby
before_script:
  - bundle install
script:
  - rubocop --fail-level=W
  - rake test
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
deploy:
  provider: rubygems
  api_key:
    secure: PRNz0pPyO99KdYcQ1WKkunc3TOz1N5ZmdT997KlzRYa5uos+IFqr5UsztJzOrus5iWoQdKKtLGSRYe1SFnXDkSOwK61Q5YvYdSqF3OE/QD63qHub+is4CxmfMmXg+eBGreSH+kIWlSD8N3ic2CDZR8JoQmhPcit6zCZSN3WVRfY=
  gem: smtpapi
  on:
    tags: true
    rvm: '2.4'
    skip_cleanup: true
